Add the code to install the Hashicorp GPG key.
MonetCarriere/Project-AWS pull request #26
Opened 2024-11-04 16:56 UTC by jlotto8

It's not really possible to test  this without the other components of the script, but I ran the following it is was successful:

#!/bin/bash

# Check if Terraform is installed
if (which terraform)
then
  echo "Terraform is already installed."
  exit 0
else
  echo "Terraform is not installed. Proceeding with installation."
fi

# Check if gnupg is installed
if (which gpg)
then
  echo "gnupg is already installed."
else
  echo "Installing gnupg"
  sudo apt-get install -y gnupg
fi

# Check if software-properties-common is installed
if (dpkg -s software-properties-common > /dev/null 2>&1)
then
  echo "software-properties-common is already installed."
else
  echo "Installing software-properties-common"
  sudo apt-get install -y software-properties-common
fi

# Check if the HashiCorp repository is added by looking for "hashicorp" in apt-cache policy output
if apt-cache policy | grep -q 'https://apt.releases.hashicorp.com'
then
  echo "HashiCorp repository is already present. Skipping addition of GPG key and repository."
else
  echo "Adding the HashiCorp GPG key and repository."

  # Add the HashiCorp GPG key using apt-key
  sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AA16FCBCA621E701

  # Add the official HashiCorp Linux repository to the sources list
  sudo sh -c 'echo "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list'

  # Update the package list to recognize the HashiCorp repository
  sudo apt-get update
fi

# Install Terraform
echo "Installing Terraform"
sudo apt-get install -y terraform

echo "Terraform installed successfully."

2024-11-04 17:15 UTC, stephenlauck commented
I'm not sure where these `exit 0` came from, but you don't want to exit out of the script. You want the whole thing to run.

2024-11-04 17:46 UTC, Topher2014 approved these changes

2024-11-04 17:53 UTC, DevinBeu commented
> I'm not sure where these `exit 0` came from, but you don't want to exit out of the script. You want the whole thing to run.

If the `if (which terraform)`
command returns a truthy value, then we already have the desired state, correct? Why would we need to run the rest of the script if we already have the desired state?

2024-11-04 19:35 UTC, stephenlauck approved these changes
Yup that's it.

2024-11-04 19:40 UTC, stephenlauck commented
> > I'm not sure where these `exit 0` came from, but you don't want to exit out of the script. You want the whole thing to run.
> 
> If the `if (which terraform)` command returns a truthy value, then we already have the desired state, correct? Why would we need to run the rest of the script if we already have the desired state?

You want to run the rest of the script because it contains other things that need to be true. If you exit 0 in that first IF block, it exits the script.

2024-11-04 23:04 UTC, DevinBeu requested changes
this part 
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AA16FCBCA621E701`
apt key is deprecated. if we are installing gpg we should use gpg command explicitly. The apt key command uses gpg for us under the hood, its been deprecated for security reasons? I vote for explicitly using gpg command

2024-11-05 02:31 UTC, stephenlauck commented
> this part `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AA16FCBCA621E701` apt key is deprecated. if we are installing gpg we should use gpg command explicitly. The apt key command uses gpg for us under the hood, its been deprecated for security reasons? I vote for explicitly using gpg command

```
# docker.gpg is in the keyring

gpg /etc/apt/keyrings/docker.gpg

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

2024-11-05 17:39 UTC, closed without merging